import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* 
         Removed bg-gray-50 and added bg-background 
         to use your soft, calm gray-blue theme 
      */}
      <body className="min-h-screen bg-background text-foreground antialiased selection:bg-primary/20 selection:text-primary">
        
        {/* The Navbar now floats with its blur effect */}
        <Navbar />

        {/* 
           Main container: 
           Added a max-width so your "Minimessage" app 
           doesn't get too wide on big boxing-sized monitors 
        */}
        <main className="mx-auto max-w-7xl p-6 md:p-10">
          {children}
        </main>

      </body>
    </html>
  );
}
